@echo on
cd /d C:\Programmation\tb-1\src
call "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
mkdir ..\bin 2>nul
cl /c /O2 /DNDEBUG /D_HAS_EXCEPTIONS=0 /std:c++17 /I. /DREGULAR /DMAGIC /DUSE_POPCNT /DTBPIECES=7 /D"COMPRESSION_THREADS=6" tbgen.c
cl /c /O2 /DNDEBUG /D_HAS_EXCEPTIONS=0 /std:c++17 /I. /DREGULAR /DMAGIC /DUSE_POPCNT /DTBPIECES=7 /D"COMPRESSION_THREADS=6" permute.c
cl /c /O2 /DNDEBUG /D_HAS_EXCEPTIONS=0 /std:c++17 /I. /DREGULAR /DMAGIC /DUSE_POPCNT /DTBPIECES=7 /D"COMPRESSION_THREADS=6" compress.c
cl /c /O2 /DNDEBUG /D_HAS_EXCEPTIONS=0 /std:c++17 /I. /DREGULAR /DMAGIC /DUSE_POPCNT /DTBPIECES=7 /D"COMPRESSION_THREADS=6" huffman.c
cl /c /O2 /DNDEBUG /D_HAS_EXCEPTIONS=0 /std:c++17 /I. /DREGULAR /DMAGIC /DUSE_POPCNT /DTBPIECES=7 /D"COMPRESSION_THREADS=6" threads.c
cl /c /O2 /DNDEBUG /D_HAS_EXCEPTIONS=0 /std:c++17 /I. /DREGULAR /DMAGIC /DUSE_POPCNT /DTBPIECES=7 /D"COMPRESSION_THREADS=6" lz4.c
cl /c /O2 /DNDEBUG /D_HAS_EXCEPTIONS=0 /std:c++17 /I. /DREGULAR /DMAGIC /DUSE_POPCNT /DTBPIECES=7 /D"COMPRESSION_THREADS=6" checksum.c
cl /c /O2 /DNDEBUG /D_HAS_EXCEPTIONS=0 /std:c++17 /I. /DREGULAR /DMAGIC /DUSE_POPCNT /DTBPIECES=7 /D"COMPRESSION_THREADS=6" city-c.c
cl /c /O2 /DNDEBUG /D_HAS_EXCEPTIONS=0 /std:c++17 /I. /DREGULAR /DMAGIC /DUSE_POPCNT /DTBPIECES=7 /D"COMPRESSION_THREADS=6" util.c
link /OUT:..\bin\tbgen.exe tbgen.obj permute.obj compress.obj huffman.obj threads.obj lz4.obj checksum.obj city-c.obj util.obj /SUBSYSTEM:CONSOLE