GENTBNAME = ../bin/stbgen.exe
GENTBPNAME = ../bin/stbgenp.exe
VERTBNAME = ../bin/stbver.exe
VERTBPNAME = ../bin/stbverp.exe
CLEAN = sclean

DEPDIR = .depss
OBJDIR = objss

FLAGS += -DSUICIDE

include Makefile.general

