GENTBNAME = ../bin/rtbgenp.exe
GENTBPNAME = ../bin/rtbgenp.exe
VERTBNAME = ../bin/rtbverp.exe
VERTBPNAME = ../bin/rtbverp.exe
CLEAN = pclean

DEPDIR = .debsp
OBJDIR = objsp

CFLAGS_PAWNFUL = -O2 -march=native -pipe -D_GNU_SOURCE -Wall -std=c11 -flto=auto
CFLAGS_PAWNFUL += -DMAGIC -DUSE_POPCNT -DTBPIECES=7 -DCOMPRESSION_THREADS=6 -DREGULAR -DHAS_PAWNS

TBOBJS = tbgen.o tbgenp.o permute.o compress.o huffman.o threads.o lz4.o tbver.o tbverp.o decompress.o checksum.o city-c.o tbcheck.o util.o
GENTBOBJS = tbgen.o permute.o compress.o huffman.o threads.o lz4.o checksum.o city-c.o util.o
GENTBPOBJS = tbgenp.o permute.o compress.o huffman.o threads.o lz4.o checksum.o city-c.o util.o
VERTBOBJS = tbver.o decompress.o threads.o checksum.o city-c.o util.o
VERTBPOBJS = tbverp.o decompress.o threads.o checksum.o city-c.o util.o

TBCHECKOBJS = tbcheck.o threads.o checksum.o city-c.o lz4.o util.o

CFILES = tbgen.c tbgenp.c tbver.c tbverp.c permute.c compress.c huffman.c threads.c lz4.c decompress.c checksum.c city-c.c tbcheck.c util.c
include $(CFILES:%.c=$(DEPDIR)/%.P)
include $(TBOBJS:%.o=$(DEPDIR)/%.P)

$(GENTBNAME): $(GENTBOBJS)
	@mkdir -p $(dir $(GENTBNAME))
	$(CC) $(CFLAGS) -o $(GENTBNAME) $(OBJDIR)/tbgen.o $(OBJDIR)/permute.o $(OBJDIR)/compress.o $(OBJDIR)/huffman.o $(OBJDIR)/threads.o $(OBJDIR)/lz4.o $(OBJDIR)/checksum.o $(OBJDIR)/city-c.o $(OBJDIR)/util.o $(LDFLAGS)

$(GENTBPNAME): $(GENTBPOBJS)
	@mkdir -p $(dir $(GENTBPNAME))
	$(CC) $(CFLAGS_PAWNFUL) -o $(GENTBPNAME) $(OBJDIR)/tbgenp.o $(OBJDIR)/permute.o $(OBJDIR)/compress.o $(OBJDIR)/huffman.o $(OBJDIR)/threads.o $(OBJDIR)/lz4.o $(OBJDIR)/checksum.o $(OBJDIR)/city-c.o $(OBJDIR)/util.o $(LDFLAGS)

$(VERTBNAME): $(VERTBOBJS)
	@mkdir -p $(dir $(VERTBNAME))
	$(CC) $(CFLAGS) -o $(VERTBNAME) $(VERTBOBJS:%=$(OBJDIR)/%) $(LDFLAGS)

$(VERTBPNAME): $(VERTBPOBJS)
	@mkdir -p $(dir $(VERTBPNAME))
	$(CC) $(CFLAGS_PAWNFUL) -o $(VERTBPNAME) $(VERTBPOBJS:%=$(OBJDIR)/%) $(LDFLAGS)

tbcheck: $(TBCHECKOBJS)
	@mkdir -p $(dir tbcheck)
	$(CC) $(CFLAGS) -o tbcheck $(TBCHECKOBJS:%=$(OBJDIR)/%)

%.o $(OBJDIR)/%.o: %.c
	@mkdir -p $(OBJDIR)
	$(CC) $(CFLAGS) -c $*.c $(FLAGS) -o $(OBJDIR)/$*.o

$(DEPDIR)/%.P: %.c
	@mkdir -p $(DEPDIR)
	$(SHELL) -ec '$(CC) -M $(FLAGS) $*.c | sed s/$*\.o/$*\.o\ $*\.P/ >$@'

$(CLEAN):
	rm -f $(TBOBJS:%=$(OBJDIR)/%)

rtbgenp: $(GENTBPNAME)
	@cp $(GENTBPNAME) $(GENTBNAME)

rtbverp: $(VERTBPNAME)
	@cp $(VERTBPNAME) $(VERTBPNAME)