GENTBNAME = ../bin/rtbgen.exe
GENTBPNAME = ../bin/rtbgenp.exe
VERTBNAME = ../bin/rtbver.exe
VERTBPNAME = ../bin/rtbverp.exe
CLEAN = clean

DEPDIR = .depsr
OBJDIR = objsr

FLAGS += -DREGULAR

include Makefile.general

