GENTBNAME = ../bin/gtbgen.exe
GENTBPNAME = ../bin/gtbgenp.exe
VERTBNAME = ../bin/gtbver.exe
VERTBPNAME = ../bin/gtbverp.exe
CLEAN = gclean

DEPDIR = .depsg
OBJDIR = objsg

FLAGS += -DGIVEAWAY

include Makefile.general

