GENTBNAME = ../bin/jtbgen.exe
GENTBPNAME = ../bin/jtbgenp.exe
VERTBNAME = ../bin/jtbver.exe
VERTBPNAME = ../bin/jtbverp.exe
CLEAN = jclean

DEPDIR = .depsj
OBJDIR = objsj

FLAGS += -DSHATRANJ

include Makefile.general

