GENTBNAME = ../bin/atbgen.exe
GENTBPNAME = ../bin/atbgenp.exe
VERTBNAME = ../bin/atbver.exe
VERTBPNAME = ../bin/atbverp.exe
CLEAN = aclean

DEPDIR = .depsa
OBJDIR = objsa

FLAGS += -DATOMIC

include Makefile.general

